site_name: Blender Launcher
site_description: Standalone client for managing official builds of Blender 3D
nav:
    - Home: index.md
    - Installation: installation.md
    - User Interface: user_interface.md
    - Library Folder: library_folder.md
    - Settings: settings.md
    - Manual Blender Installation: manual_build_installation.md
    - Build Initialization: build_initialization.md
    - File Association: file_association.md
    - Troubleshooting: troubleshooting.md
    - Known Issues: known_issues.md
    - Feature Request: feature_request.md
    - Development: development.md
docs_dir: mkdocs
site_dir: site
theme:
    name: material
    palette:
        scheme: slate
        primary: black
        accent: pink
    features:
        - navigation.instant
        - search.suggest
        - search.highlight
        - content.code.copy
    favicon: icons/favicon.ico
    logo: icons/favicon.ico
markdown_extensions:
    - smarty
    - admonition
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - attr_list
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - def_list
    - pymdownx.critic:
        mode: view
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
        permalink: true
plugins:
  - search:
      lang: en
extra_css:
    - stylesheets/extra.css
repo_url: https://github.com/Victor-IX/Blender-Launcher-V2
edit_uri: ""
copyright: Copyright &copy; 2022 Victor Chedeville │ Blender Launcher GPL-3.0 License │ Version 2.3.0
