name: Submit Winget Package to Windows Package Manager Community Repository
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Specific tag name"
        required: false
        type: string
jobs:
  winget-publish:
    name: Publish winget package
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.release.tag_name, '-rc')}}
    steps:
      - name: Set winget version env
        env:
          TAG_NAME: ${{ inputs.tag_name || github.event.release.tag_name }}
        run: echo "WINGET_TAG_NAME=$(echo ${TAG_NAME#v})" >> $GITHUB_ENV
      - name: Submit package to Windows Package Manager Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: VictorIX.BlenderLauncher
          installers-regex: '^Blender_Launcher_v[\d\.]+_Windows_x64\.zip$'
          version: ${{ env.WINGET_TAG_NAME }}
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
          token: ${{ secrets.WINGET_ACC_TOKEN }}
          # fork-user: Victor-IX
